### ISSUE TITLE
Webpack 环境细节制定

### ISSUE THREAD

**Issue by jiyinyiyong** [react-china/forum-frontend#4]

**Comment by shane13hsi** [comment]
建议：

- dev 开发环境，hot reload，这块 webpack 配置简单，示例：https://github.com/shane13hsi/bee/blob/master/webpack/webpack-dev.config.js
- product 生产环境，配置复杂
- test 测试，webpack 配置简单，直接放到 karma.conf 中，示例：https://github.com/shane13hsi/bee/blob/master/karma.conf.js

**Comment by uooo** [comment]
最近正在尝试基于 npm 和 webpack 的业务分模块协同开发，大牛们来指点下。

文章参考 [前端工程——基础篇](https://github.com/fouber/blog/issues/10)

**Comment by fraserxu** [comment]
Done, closing.
