### ISSUE TITLE
技术工具选型

### ISSUE THREAD

**Issue by uooo** [react-china/forum-frontend#7]
参考列表：
* [React](http://facebook.github.io/react/)
* [immutable.js](http://facebook.github.io/immutable-js)
* ECMAScript 2015+ with [Babel](https://babeljs.io/). [JSX](http://facebook.github.io/react/docs/jsx-in-depth.html) and [Flowtype](http://flowtype.org/) syntax supported
* [webpack](http://webpack.github.io/)
* [eslint ES6](http://eslint.org/) linting with [React](https://github.com/yannickcr/eslint-plugin-react) JSX support.
* 国际化
  - [formatjs.io](http://formatjs.io/)
* 路由？
* ajax
  - superagent
  - fetch
* UI
  - [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap)

**Comment by geminiyellow** [comment]
StyleCheck: 
- [ESLint](http://eslint.org/)

Build: 
- [Webpack](http://webpack.github.io/)

Test:
- [Karma](http://karma-runner.github.io/0.13/index.html)
- [Jasmine](http://jasmine.github.io/)

**Comment by xcatliu** [comment]
Flux:
- [redux](https://github.com/rackt/redux)

**Comment by xcatliu** [comment]
Test:
- [tape](https://github.com/substack/tape)

**Comment by szhclaye** [comment]
支持redux

**Comment by idisblueflash** [comment]
Test:
- karma( mocha, chai, sinon )

**Comment by fraserxu** [comment]
建议推荐技术的时候添加上推荐理由。
