### ISSUE TITLE
移动版？React Native？

### ISSUE THREAD

**Issue by xcatliu** [react-china/forum-frontend#8]

**Comment by jiyinyiyong** [comment]
如果有人维护的话, 可以建立一个新的仓库分配权限.

**Comment by Justinidlerz** [comment]
建议移动版可以先由React实现Discourse ，再将模块重新组合拼接而成

**Comment by geminiyellow** [comment]
建议另起 repo。

**Comment by xcatliu** [comment]
@Justinidlerz 

> 建议移动版可以先由React实现Discourse ，再将模块重新组合拼接而成

具体是什么意思呢？

**Comment by xcatliu** [comment]
@jiyinyiyong 建一个 repo 吧，我有兴趣做。

**Comment by jiyinyiyong** [comment]
@xcatliu 交给你了~ https://github.com/react-china/forum-native

**Comment by xcatliu** [comment]
@jiyinyiyong 赞~
