### ISSUE TITLE
目录结构规划

### ISSUE THREAD

**Issue by uooo** [react-china/forum-frontend#9]

**Comment by Justinidlerz** [comment]
项目基础路径规范可否参考Redux的example中todoMVC的结构，前段时间比较仔细的就看了一下这个项目，结构上还是值得参考，但在components上可能看路由情况再做划分。

**Comment by Saber-Kurama** [comment]
我觉得Redux的结构挺好的，组件的话，是不是可以划分两个目录，一个公共的组件一个具体功能的组件。

**Comment by geminiyellow** [comment]
#26 按照 Redux 的格式推送了。
工程模块不多，这种划分是可以的。
我更喜欢的是按照模块来划分。参考 [LEFT](https://github.com/johnpapa/angular-styleguide#application-structure-lift-principle)。

我的想法:
 
### 数据流和UI

`redux` 和 `react-router` 是没关系的两个东西。只是按照功能模块来划分的话。在每个页面上，
都应该存在 `redux` 的 `reducer`, `react-router` 的 `router`。

### 组织划分

考虑类似 ng 的 module 方式。在每个 module 的 index 中，将该 module 的 router 和 reducer invoke 到 app 主干里面。

最后 app 中只有唯一函数 bootstrap(element, initiaState) 。也就是 mount 的元素，以及 store 的初始值。

### 目录

```
app/
-- shared/
---- sidebar/
------ index.js
------ sidebarActions.js
------ sidebarReducer.js
------ sidebarView.jsx
-- modules/
---- home/
------ index.js
------ homeActions.js
------ homeReducer.js
------ homeView.jsx
---- settings/
------ index.js
------ settingsActions.js
------ settingsReducer.js
------ settingsView.jsx
-- app.module.js
```

**Comment by hysios** [comment]
@geminiyellow  react 按这种方式还需要考虑一下

**Comment by uooo** [comment]
还得考虑 CSS 及其他静态资源的模块化，是不是按模块放 CSS

**Comment by geminiyellow** [comment]
@hysios 比如说。

**Comment by geminiyellow** [comment]
@uooo Sass 模块化呗。

**Comment by Saber-Kurama** [comment]
如果功能模块分很多的话，这样的分法是可以考虑下的。但是个人觉得每个功能模块应该按照Redux 的格式来分。大致应该是这样(其实和你一样，就是多了目录)

````
app/
-- components/
-- home/
-- -- actions/
-- -- reducers/
-- -- components/
-- -- stylesheets/
-- -- images/
-- -- index.js

````

当然 这块关于静态资源工程打包的时候得注意路径问题吧。
